In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import librosa

In [2]:
x, sr = librosa.load('speaker01_0_1.wav')

In [3]:
x

array([ 8.4030122e-05,  1.4463621e-06, -1.5069517e-04, ...,
       -1.1635182e-04, -1.6466103e-05, -1.3998925e-04], dtype=float32)

In [4]:
sr

22050

In [5]:
mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)

In [6]:
x, sr = librosa.load('speaker01_0_2.wav')
mfccs1 = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
mfccs.shape

(13, 38)

In [7]:
maxi = []
for i in range(1,7):
  for j in range(1,6):
      x, sr = librosa.load('speaker0'+str(i) + '_0_'+str(j)+'.wav')
      mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
      maxi.append(mfccs.shape[1])
maxi
max_shape = max(maxi)
max_shape


41

In [8]:
print(mfccs.shape)
mfccs1 = np.matrix(mfccs)
mfccs2 = mfccs1.transpose()
mfccs2.shape

(13, 29)


(29, 13)

In [9]:
mfccs2[0][0]

matrix([[-248.91078  ,   81.22266  ,  -28.124432 ,   95.61183  ,
          -25.963129 ,   43.16329  ,  -32.195374 ,  -15.09482  ,
           -1.4165797,   -5.505769 ,   -6.1422987,  -18.020033 ,
            0.7662223]], dtype=float32)

In [10]:
def rotate(mfccs):
  q = []
  for i in range(mfccs.shape[0]):
    p = []
    for j in range(mfccs.shape[1]):
      p.append(mfccs[j][i])
    q.append(p)
  return q
    

In [11]:
# mfcc_0=[]
# mfcc_1=[]
# mfcc_2=[]
# mfcc_3=[]
# mfcc_4=[]
# mfcc_5=[]
# mfcc_6=[]
# mfcc_7=[]
# mfcc_8=[]
# mfcc_9=[]
# mfcc_final = [mfcc_0,mfcc_1,mfcc_2,mfcc_3,mfcc_4,mfcc_5,mfcc_6,mfcc_7,mfcc_8,mfcc_9]
# mfcc_final[0]

In [12]:
mfcc_final=[]
for k in range(10):
  r=[]
  for i in range(1,7):
  # ans = []
    for j in range(1,6):
      x, sr = librosa.load('speaker0'+str(i) + '_'+str(k)+'_'+str(j)+'.wav')
      mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
    # print(mfccs.shape)
      mfccs1 = np.matrix(mfccs)
      mfccs2 = mfccs1.transpose()
    # print(mfccs2.shape[0])
    # print(mfccs.shape)
      for y in range(mfccs2.shape[0]):
        r.append(mfccs2[y])
    # mfcc_0.append(list(mfccs2))
    # print(len(mfcc_0))
  # print(len(r))
  mfcc_final.append(r)
  print(len(mfcc_final[k]))
       

1001
848
977
913
968
884
800
950
912
903


In [13]:
# mfcc_1=[]
# r=[]
# for i in range(1,7):
#   # ans = []
#   for j in range(1,6):
#     x, sr = librosa.load('speaker0'+str(i) + '_1_'+str(j)+'.wav')
#     mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#     # print(mfccs.shape)
#     mfccs1 = np.matrix(mfccs)
#     mfccs2 = mfccs1.transpose()
#     # print(mfccs2.shape[0])
#     # print(mfccs.shape)
#     for y in range(mfccs2.shape[0]):
#       mfcc_1.append(mfccs2[y])
#     # mfcc_0.append(list(mfccs2))
#     # print(len(mfcc_0))
# print(len(mfcc_1))

In [14]:
# mfcc_0 = []
# for i in range(1,7):
#   for j in range(1,6):
#       x, sr = librosa.load('speaker0'+str(i) + '_0_'+str(j)+'.wav')
#       mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#       for k in range(13): 
#         mfcc_0.append(list(mfccs[k]))    
# # np.array(mfcc_0).shape
# np.array(mfcc_0[0]).shape
# len(mfcc_0[13])

In [15]:
# from sklearn.cluster import KMeans
# import numpy as np
# # >>> X = np.array([[1, 2], [1, 4], [1, 0],
# # ...               [10, 2], [10, 4], [10, 0]])
# kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(X)
# kmeans.labels_

In [16]:
mfcc_test=[]
for k in range(10):
  r=[]
  for i in range(1,5):
  # ans = []
    for j in range(8,11):
      x, sr = librosa.load('speaker0'+str(i) + '_'+str(k)+'_'+str(j)+'.wav')
      mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
    # print(mfccs.shape)
      mfccs1 = np.matrix(mfccs)
      mfccs2 = mfccs1.transpose()
    # print(mfccs2.shape[0])
    # print(mfccs.shape)
      for y in range(mfccs2.shape[0]):
        r.append(mfccs2[y])
    # mfcc_0.append(list(mfccs2))
    # print(len(mfcc_0))
  # print(len(r))
  mfcc_test.append(r)
  print(len(mfcc_test[k]))

425
344
401
368
404
350
327
384
373
377


In [17]:
x, sr = librosa.load('speaker01_2_8.wav')
mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)

In [18]:
mfcc_final[0][0]
print(mfccs.shape)
mfccs = np.matrix(mfccs)
mfccs = mfccs.transpose()
print(mfccs.shape)
mfccs[0]

(13, 37)
(37, 13)


matrix([[-514.2872    ,   36.694153  ,   -6.6972837 ,   -2.4551136 ,
           -5.763338  ,   -0.99557865,   -5.6253724 ,   -7.3749638 ,
          -12.088687  ,   -4.627123  ,    0.97837156,   -4.4846864 ,
            8.020094  ]], dtype=float32)

In [19]:
import math
distance = []
distance_final=[[] for i in range(mfccs.shape[0])]
for k in range(mfccs.shape[0]):
  p = math.inf
  q = 0
  distance = []
  dist = 0
  for i in range(len(mfcc_final)):
    for j in range(len(mfcc_final[i])):
      dist = dist +  np.linalg.norm(mfccs[k] - mfcc_final[i][j])
    dist = dist/len(mfcc_final[i])
    # if(dist<p):
    #   p = dist
    #   q = i
    distance.append(dist)
  # print(len(distance))
  d = min(distance)
  t = distance.index(d)
  distance_final[k].append(min(distance))
  distance_final[k].append(t)
    

In [20]:
len(distance_final)

37

In [21]:
distance_final

[[186.14202799303797, 2],
 [173.75722260957974, 2],
 [170.96291193794482, 2],
 [171.68064801186569, 2],
 [172.1852477404787, 2],
 [170.39000967648352, 2],
 [166.95299863411796, 2],
 [183.4633842035306, 4],
 [216.3095677838809, 4],
 [221.08425238524364, 4],
 [207.4615099247518, 4],
 [202.13882505926534, 4],
 [200.80373789575404, 4],
 [197.03538899966784, 2],
 [197.7932980806762, 2],
 [199.33223372487163, 2],
 [200.47777892146988, 2],
 [205.13700664531194, 2],
 [205.39922253968217, 2],
 [207.06612431856007, 2],
 [205.14579035283973, 2],
 [201.6344601737926, 2],
 [199.96690962525506, 2],
 [196.1823919235839, 2],
 [190.0008481910722, 2],
 [181.0653247232661, 2],
 [173.56970752972668, 2],
 [168.19201954157398, 2],
 [168.27832823544887, 2],
 [173.9296392483135, 2],
 [182.5907470271691, 2],
 [190.5614093148312, 2],
 [200.39330890769642, 2],
 [210.9986274491124, 2],
 [218.17440388131521, 2],
 [219.6503116205645, 2],
 [222.10257679026637, 2]]

In [22]:
# w = []
# for i in range(10):
#   w.append(distance.count(i))
# w

In [23]:
# for i in range(len(mfcc_0)):
#   if(len(mfcc_0[i])< max_shape):
#     diff = max_shape - len(mfcc_0[i])
#     for j in range(diff):
#       mfcc_0[i].append(0)
# len(mfcc_0[13])

In [24]:
# sum = np.array([ 0 for l in range(max_shape)])
# for i in range(len(mfcc_0)):
#   sum = sum + np.array(mfcc_0[i])
# sum
# mfcc_0_final = np.array(sum)/(max_shape)
# mfcc_0_final

In [25]:
# mfcc_final = []
# #digit 1
# # mfcc_digit = [mfcc_0,mfcc_1,mfcc_2,mfcc_3,mfcc_4,mfcc_5,mfcc_6,mfcc_7,mfcc_8,mfcc_9]
# count = 0
# for m in range(10):
#   maxi = []
#   for i in range(1,7):
#     for j in range(1,6):
#         x, sr = librosa.load('speaker0'+str(i) + '_'+str(m)+'_'+str(j)+'.wav')
#         count = count + 1
#         mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#         maxi.append(mfccs.shape[1])
# # maxi
#   max_shape = max(maxi)
#   print(max_shape)

#   mfcc_digit = []
#   for i in range(1,7):
#     for j in range(1,6):
#         x, sr = librosa.load('speaker0'+str(i) + '_'+str(m)+'_'+str(j)+'.wav')
#         mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#         for k in range(13): 
#           mfcc_digit.append(list(mfccs[k]))    
# # np.array(mfcc_0).shape
#   print(np.array(mfcc_digit).shape)
#   # len(mfcc_di[13])

#   for i in range(len(mfcc_digit)):
#     if(len(mfcc_digit[i])< max_shape):
#       diff = max_shape - len(mfcc_digit[i])
#       for j in range(diff):
#         mfcc_digit[i].append(0)
#     mfcc_final.append(mfcc_digit[i])
#   print(np.array(mfcc_final).shape)
#   # len(mfcc_1[13])

#   # sum = np.array([ 0 for l in range(max_shape)])
#   # for i in range(len(mfcc_digit)):
#   #   sum = sum + np.array(mfcc_digit[i])
#   # sum
#   # mfcc_digit_final = np.array(sum)/(max_shape)
   
# print(count)

In [26]:
# train = []
# for i in range(len(mfcc_final)):
#   train.append(list(mfcc_final[i]))

# mfcc_train = []
# for i in range(len(train)):
#   if(len(train[i])< 41):
#     diff = 41 - len(train[i])
#     for j in range(diff):
#       train[i].append(0)
#   mfcc_train.append(train[i])
# len(mfcc_train)

In [27]:
# from sklearn.cluster import KMeans
# kmeans = KMeans(n_clusters = 10, random_state = 0,n_init = 4).fit(mfcc_train)
# kmeans.labels_

In [28]:
# mfcc_final_test = []
# #digit 1
# # mfcc_digit = [mfcc_0,mfcc_1,mfcc_2,mfcc_3,mfcc_4,mfcc_5,mfcc_6,mfcc_7,mfcc_8,mfcc_9]
# count = 0
# for m in range(10):
#   maxi = []
#   for i in range(1,5):
#     for j in range(8,11):
#         x, sr = librosa.load('speaker0'+str(i) + '_'+str(m)+'_'+str(j)+'.wav')
#         count = count + 1
#         mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#         maxi.append(mfccs.shape[1])
# # maxi
#   max_shape = max(maxi)
#   print(max_shape)

#   mfcc_digit = []
#   for i in range(1,5):
#     for j in range(8,11):
#         x, sr = librosa.load('speaker0'+str(i) + '_'+str(m)+'_'+str(j)+'.wav')
#         mfccs = librosa.feature.mfcc(y=x,sr=sr,n_mfcc=13)
#         for k in range(13): 
#           mfcc_digit.append(list(mfccs[k]))    
# # np.array(mfcc_0).shape
#   np.array(mfcc_digit[0]).shape
#   # len(mfcc_di[13])

#   for i in range(len(mfcc_digit)):
#     if(len(mfcc_digit[i])< max_shape):
#       diff = max_shape - len(mfcc_digit[i])
#       for j in range(diff):
#         mfcc_digit[i].append(0)
#   # len(mfcc_1[13])

#   # sum = np.array([ 0 for l in range(max_shape)])
#   # for i in range(len(mfcc_digit)):
#   #   sum = sum + np.array(mfcc_digit[i])
#   # sum
#   # mfcc_digit_final = np.array(sum)/(max_shape)
#     mfcc_final_test.append(mfcc_digit[i])
# print(count)

In [29]:
# test = []
# for i in range(len(mfcc_final_test)):
#   test.append(list(mfcc_final_test[i]))

# mfcc_test = []
# for i in range(len(test)):
#   if(len(test[i])< 41):
#     diff = 41 - len(test[i])
#     for j in range(diff):
#       test[i].append(0)
#   mfcc_test.append(test[i])

In [30]:
# train = []
# for i in range(len(mfcc_final)):
#   train.append(list(mfcc_final[i]))

# mfcc_train = []
# for i in range(len(train)):
#   if(len(train[i])< 41):
#     diff = 41 - len(train[i])
#     for j in range(diff):
#       train[i].append(0)
#   mfcc_train.append(train[i])

In [31]:
# len(mfcc_train)

In [32]:
# distance = []
# for i in range(len(mfcc_test)):
#   dist = []
#   for j in range(len(mfcc_train)):
#     dist.append(np.linalg.norm(np.array(mfcc_test[i]) - np.array(mfcc_train[j])))
#   print(dist)
#   distance.append(dist.index(min(dist)))

In [33]:
# distance